# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/fastpolvo',
                'doc_host': 'https://lgvaz.github.io',
                'git_url': 'https://github.com/lgvaz/fastpolvo',
                'lib_path': 'fastpolvo'},
  'syms': { 'fastpolvo.classification.explorer': { 'fastpolvo.classification.explorer.DataExplorer': ( 'classification.explorer.html#dataexplorer',
                                                                                                       'fastpolvo/classification/explorer.py'),
                                                   'fastpolvo.classification.explorer.DataExplorer.__init__': ( 'classification.explorer.html#dataexplorer.__init__',
                                                                                                                'fastpolvo/classification/explorer.py'),
                                                   'fastpolvo.classification.explorer.DataExplorer.from_datasets': ( 'classification.explorer.html#dataexplorer.from_datasets',
                                                                                                                     'fastpolvo/classification/explorer.py')},
            'fastpolvo.core': { 'fastpolvo.core.one_batch_with_idxs': ('core.html#one_batch_with_idxs', 'fastpolvo/core.py'),
                                'fastpolvo.core.show_tfms': ('core.html#show_tfms', 'fastpolvo/core.py')}}}
